### ISSUE TITLE
sun3.php browser issue

### ISSUE THREAD

**Issue by steepleian** [ktrue/CU-HWS#21]
Ken
Users reporting that sun3.php not working correctly on Firefox and Safari (including ios versions). The small solid circle representing the passage of the sun does not show. Seemingly only working with Chrome.

I have been able to replicate the problem as reported.

**Comment by ktrue** [comment]
Ok, that is strange.  In Firefox Developer browser, it shows the solid circle just fine and tracks.
On Firefox 64.0.2 it doesn't show.
On Chrome 71.0.3578.98 it shows fine.
On Edge it doesn't show
On IE11 it doesn't show
On Opera 57.0.3098.116 it shows fine.

All the browsers seem to show Wim's sun_block.php just fine so I guess I didn't quite clone it correctly.
I'll work up a fix for the module.. thanks for spotting the problem.

**Comment by ktrue** [comment]
Whew.. I think I fixed it.  The issue was in trying to draw a zero-distance arc representing the sun.  It worked ok on Chrome/Opera/Firefox Developer, but not on Firefox/Edge/IE.

I added code to actually draw a circle at the correct position on the 24hr sun arc and it works in all browsers.  Dang, I'm getting too old for geometry questions.

**Comment by steepleian** [comment]
Perfect Ken,
If you are too old for geometry then at my age I cant even remember what a
compass is for!

Thanks for such a rapid response and fix,
Regards,
Ian
